language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-spiffy' ]; then cd .. && eval "mv $currentfolder generator-spiffy" && cd generator-spiffy; fi
